### ISSUE TITLE
Labels don't get removed if the PR's are closed and from other authors

### ISSUE THREAD

**Issue by stavares843** [rogerluan/label-remover#266] opened 2021-12-18 22:07 UTC
Hello! 👋 

I noticed the following when using this Github Action
- any merged PR with a label, any labels there are removed ✅ 

<img width="939" alt="Captura de ecrã 2021-12-18, às 22 01 12" src="https://user-images.githubusercontent.com/29093946/146656572-55627efc-41f0-4962-8597-52343e885a23.png">

- if you are the PR author, add a PR, close it without merging it, labels get removed as well ✅ 

<img width="949" alt="Captura de ecrã 2021-12-18, às 21 59 36" src="https://user-images.githubusercontent.com/29093946/146656540-6bdb5da6-647f-46e6-b5c4-5cbaf3e861ee.png">

- if you are not the PR author, add a PR, close it without merging it, any labels that are there don't get removed ❌ 

note - the closed PR's are not from the forked branch's

version - `rogerluan/label-remover@v1.0.1`

repro rate - 5/5

**Comment by rogerluan** [comment] 2021-12-19 15:10
Hi @stavares843 ! Thanks for your report.

I believe this behavior you're seeing is due to a recent GitHub change, where PRs authored by outside contributors won't run the GitHub Actions until a repo maintainer with write access gives the green light. You can read more about this new restriction here: https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

In other words: if the PR is open by someone the repo doesn't trust yet, it won't run GitHub Actions. 

As seen [here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), you can approve those PRs to run GitHub Actions, and then it will be able to run. You can do that before closin/merging the PR, for instance. Screenshot:


![](https://docs.github.com/assets/cb-54345/images/help/pull_requests/actions-approve-and-run-workflows-from-fork.png)


I hope this helps! Let me know if that's not the case, or if you have further questions 😊

**Comment by stavares843** [comment] 2021-12-19 15:55
Hello! 👋 Thanks for sending those! 

I believe it's not the issue because this also happens whenever an admin or even a repo owner himself opens a PR and then closes it, without merging it.

Going to Github Actions, still appeared as green, even if on the PR itself no labels were removed

I'm on an open-source project, you can see the log of the Github Action [here](https://github.com/Satellite-im/Core-PWA/runs/4420688624?check_suite_focus=true). This log is related to a PR where the author is a trusted author on the repo, added a repo, closed it and the labels weren't removed.


Thanks for checking! 🎉  Let me know if you need any more info 😄

**Comment by rogerluan** [comment] 2021-12-19 23:14
Hmm, interesting. It's still not clear to me the steps to reproduce, though. Let's consider the following scenario, could you help clarify the questions below? 🙏 

1. In repo `john/tool`
2. User `bob` opens a PR:
    - From `john/tool` repo, or from a forked repo e.g. `bob/tool`?
    - What is bob's relation to `john/tool` repo? e.g. contributor, first time contributor (aka untrusted user), member, owner…?
3. Someone adds labels to the PR (it doesn't matter who)
4. Someone closes the PR:
    - Who? `bob`? `john`? Someone else?
    - What's the user's relation to `john/tool` repo? e.g. contributor, first time contributor (aka untrusted user), member, owner…?
5. Expected behavior: all labels are removed by the GitHub Action, but in reality the GitHub Action runs but it doesn't remove any labels.

----

If you can find another log like you sent, that could be helpful. Unfortunately, looks like the log you provided comes from this PR https://github.com/Satellite-im/Core-PWA/pull/464 but that PR never had any labels so it didn't have any labels to be removed 🤷 

Thanks once again 💪

**Comment by stavares843** [comment] 2021-12-20 00:08
ohh wow 😂 

I thought that Github Action was about this [one](https://github.com/Satellite-im/Core-PWA/pull/461) - closed without being merged, labels not removed (it has the same branch name compared to the one you mentioned above 😂 )


gonna try to find another one 🔨  update: couldn't find any log related to a PR that was closed and Github Action didn't remove the labels, but I have PR's as samples in case that's useful:

Member A added PR, member B closed PR - [sample 1](https://github.com/Satellite-im/Core-PWA/pull/475) - labels not removed by Github Action ❌ 
Member A added PR, member A closed PR - [sample 2](https://github.com/Satellite-im/Core-PWA/pull/623) -  labels not removed by Github Action ❌ 

note - from those same users, works fine if the PR gets merged, instead of closed without being merged.

about the questions 📖 

1. In repo john/tool
2. User bob opens a PR:
- From john/tool repo, or from a forked repo e.g. bob/tool?  - `from john/tool repo`
- What is bob's relation to john/tool repo? e.g. contributor, first time contributor (aka untrusted user), member, owner…? - `I saw this behavior with member and owner`
3. Someone adds labels to the PR (it doesn't matter who)
4. Someone closes the PR:
- Who? bob? john? Someone else? - `or bob or someone else, like another member`
- What's the user's relation to john/tool repo? e.g. contributor, first time contributor (aka untrusted user), member, owner…? - `member`


Some additional notes:
- I noticed that whenever is the same author PR closing their own PR, Github Action removes the label fine, such as Bob opens the PR, Bob is a trusted member, Bob closes the PR, labels get removed.

Member A added PR, member A closed PR - [sample 1](https://github.com/Satellite-im/Core-PWA/pull/596) - labels removed by Github Action ✅ 
Member A added PR, member A closed PR - [sample 2](https://github.com/Satellite-im/Core-PWA/pull/478) - labels removed by Github Action ✅

**Comment by rogerluan** [comment] 2021-12-20 01:05
It's funny cuz these 3 scenarios (highlighted)  look the same, but 2 succeeded and 1 failed? 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/8419048/146697818-19d97175-3c39-4fe5-ad71-547bca6da53b.png">

Example of failed one: https://github.com/Satellite-im/Core-PWA/pull/623 - a member created and closed their PR and the bot didn't remove the labels.
Example of success: https://github.com/Satellite-im/Core-PWA/pull/478 - a contributor created and closed their PR and the bot removed the labels as expected.

What's happening in those that aren't removing the labels is that GitHub actions aren't running (it's not being triggered for whatever reason 😕 ). From the looks of your description, PRs provided and others I analyzed, this bug seems to be an intermittent issue.

I've seen issues with this in other projects of mine, all of them related to GitHub being down or something similar. If you check, we had downtime with GitHub Actions yesterday:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/8419048/146697910-f9c02cd6-c3e0-4711-a37e-64b5a63c4630.png">

https://www.githubstatus.com/history

Do you think this could be the reason? Any idea why GitHub Actions might not be running on those commits/PRs? 🤔

**Comment by stavares843** [comment] 2021-12-20 03:17
Thanks for checking 🎉 

Could be related, thanks for taking a look 🔨 

I believe we can close this, as it seems an issue related to Github itself. 

Again, thanks for taking a look! 😄

**Comment by rogerluan** [comment] 2021-12-21 17:38
Nah, thank _*you*_ for taking the time to report this and provide so much valuable information.

I'm closing this ticket then, please feel free to comment here again if you face this issue again so I can reopen the ticket 👍 

Enjoy the holidays! 🎄

**Closed by rogerluan** 2021-12-21 17:38 UTC
